apiVersion: apps/v1
kind: Deployment
metadata:
  name: creative-deployment
  labels:
    app: creative
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: creative
  template:
    metadata:
      labels:
        app: creative
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: creative-data
      - name: mods
        persistentVolumeClaim:
          claimName: creative-mods
          readOnly: true
      - name: config
        persistentVolumeClaim:
          claimName: creative-config
          readOnly: true
      containers:
      - name: creative
        image: itzg/minecraft-server
        imagePullPolicy: Always
        volumeMounts:
        - name: data
          mountPath: /data
        - name: mods
          mountPath: /mods
        - name: config
          mountPath: /config
        ports:
        - name: game-port
          containerPort: 25565
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 2Gi
        env:
        - name: EULA
          value: "TRUE"
        - name: VERSION
          value: "1.17.1"
        - name: TYPE
          value: "FABRIC"
        - name: MODE
          value: "creative"
        - name: FORCE_GAMEMODE
          value: "true"
        - name: OVERRIDE_SERVER_PROPERTIES
          value: "true"
        - name: ONLINE_MODE
          value: "TRUE"
        - name: REMOVE_OLD_MODS
          value: "TRUE"
        - name: ENABLE_AUTOPAUSE
          value: "TRUE"
        - name: AUTOPAUSE_TIMEOUT_EST
          value: "600"
        - name: MAX_TICK_TIME
          value: "-1"
        - name: DIFFICULTY
          value: hard
        - name: WHITELIST
          value: "maboesanman"
        - name: OPS
          value: "maboesanman"
---
apiVersion: v1
kind: Service
metadata:
  name: creative-service
spec:
  selector:
    app: creative
  ports:
  - name: default
    protocol: TCP
    port: 25565
    targetPort: 25565
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: creative-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
