apiVersion: apps/v1
kind: Deployment
metadata:
  name: survival-deployment
  labels:
    app: survival
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: survival
  template:
    metadata:
      labels:
        app: survival
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: survival-data
      - name: mods
        persistentVolumeClaim:
          claimName: survival-mods
          readOnly: true
      - name: config
        persistentVolumeClaim:
          claimName: survival-config
          readOnly: true
      containers:
      - name: survival
        image: itzg/minecraft-server
        imagePullPolicy: Always
        volumeMounts:
        - name: data
          mountPath: /data
        - name: mods
          mountPath: /mods
        - name: config
          mountPath: /config
        ports:
        - name: game-port
          containerPort: 25565
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 4000m
            memory: 8Gi
        env:
        - name: INIT_MEMORY
          value: "1500M"
        - name: MAX_MEMORY
          value: "7G"
        - name: USE_AIKAR_FLAGS
          value: "TRUE"
        - name: EULA
          value: "TRUE"
        - name: VERSION
          value: "1.17.1"
        - name: TYPE
          value: "FABRIC"
        - name: MODE
          value: "survival"
        - name: FORCE_GAMEMODE
          value: "true"
        - name: OVERRIDE_SERVER_PROPERTIES
          value: "true"
        - name: ONLINE_MODE
          value: "TRUE"
        - name: REMOVE_OLD_MODS
          value: "TRUE"
        - name: ENABLE_AUTOPAUSE
          value: "TRUE"
        - name: AUTOPAUSE_TIMEOUT_EST
          value: "600"
        - name: MAX_TICK_TIME
          value: "-1"
        - name: DIFFICULTY
          value: hard
        - name: WHITELIST
          value: "maboesanman"
        - name: OPS
          value: "maboesanman"
        - name: TZ
          value: "America/Chicago"
---
apiVersion: v1
kind: Service
metadata:
  name: survival-service
spec:
  selector:
    app: survival
  ports:
  - name: default
    protocol: TCP
    port: 25565
    targetPort: 25565
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: survival-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
