apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity-deployment
  labels:
    app: velocity
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: velocity-config
          readOnly: true
      containers:
      - name: mc-velocity
        image: itzg/bungeecord
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /config
        ports:
        - name: game-port
          containerPort: 25577
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 2Gi
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "VELOCITY"
        - name: VELOCITY_VERSION
          value: 3.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: velocity-service
spec:
  type: NodePort
  selector:
    app: velocity
  ports:
  - name: default
    protocol: TCP
    port: 25577
    targetPort: 25577
    nodePort: 32565
