apiVersion: v1
kind: PersistentVolume
metadata:
  name: survival-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Volumes/Minecraft/kubemc/survival"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: creative-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Volumes/Minecraft/kubemc/creative"
---



apiVersion: v1
kind: PersistentVolume
metadata:
  name: creative-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/tmp/minecraft/creative-config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: creative-mods
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/tmp/minecraft/creative-mods"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: survival-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/tmp/minecraft/survival-config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: survival-mods
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/tmp/minecraft/survival-mods"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: velocity-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/tmp/minecraft/velocity-config"
