apiVersion: apps/v1
kind: Deployment
metadata:
  name: creative-deployment
  labels:
    app: creative
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: creative
  template:
    metadata:
      labels:
        app: creative
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: creative-data
      containers:
      - name: creative
        image: public.ecr.aws/p2i2f2e4/minecraft-server:1.17.1-carpet
        imagePullPolicy: Always
        volumeMounts:
        - name: data
          mountPath: /data
        ports:
        - name: game-port
          containerPort: 25565
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 4000m
            memory: 8Gi
        env:
        - name: FABRIC_PROXY_SECRET
          valueFrom:
            secretKeyRef:
              name: player-forwarding-secret
              key: secret
        - name: INIT_MEMORY
          value: "1500M"
        - name: MAX_MEMORY
          value: "7G"
        - name: EULA
          value: "TRUE"
        - name: MODE
          value: "creative"
        - name: FORCE_GAMEMODE
          value: "true"
        - name: DIFFICULTY
          value: hard
        - name: WHITELIST
          value: "maboesanman"
        - name: OPS
          value: "maboesanman"
---
apiVersion: v1
kind: Service
metadata:
  name: creative-service
spec:
  selector:
    app: creative
  ports:
  - name: default
    protocol: TCP
    port: 25565
    targetPort: 25565
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: creative-data
spec:
  storageClassName: "manual"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: creative-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: creative-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Volumes/Minecraft/kubemc/creative"
