apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kubemc
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 32565
    hostPort: 25565
    listenAddress: "0.0.0.0"
    protocol: tcp
- role: worker